spring:
  datasource:
    url: jdbc:mysql://localhost:3306/landsat?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 563540228

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  port: 9090
